---
version: "1.0"
services:

  postgres-product-command:
    container_name: postgres-product-command
    image: postgres:12.12-alpine
    environment:
      POSTGRES_DB: product-command-service
      POSTGRES_USER: lenn
      POSTGRES_PASSWORD: lenn
      PG_DATA: /data/postgres
    volumes:
      - ./postgres-product-command:./data/postgres
    expose:
      - "5431"
    ports:
      - "5431:5431"
    command: -p 5431
    restart: always

  postgres-query-command:
    container_name: postgres-query-command
    image: postgres:12.12-alpine
    environment:
      POSTGRES_DB: product-query-service
      POSTGRES_USER: lenn
      POSTGRES_PASSWORD: lenn
      PG_DATA: /data/postgres
    volumes:
      - ./postgres-product-query:./data/postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    command: -p 5432
    restart: always

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.0.1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1


---