spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product-command-service
          uri: lb://product-command-service
          predicates:
            - args:
                Path: /api/product-cmd

        - id: product-query-service
          uri: lb://product-query-service
          predicates:
            - args:
                Path: /api/product-query

        - id: discovery-server
          uri: http://admin:admin@localhost:8761
          predicates:
            - args:
                Path: /eureka/web
          filters:
            - args:
                SetPath: /

        - id: discovery-server-static
          uri: http://admin:admin@localhost:8761
          predicates:
            - args:
                Path: /eureka/**

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka

server:
  port: 8080
