global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'product-command-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-command-service:8080']
        labels:
          application: "Product Command Service Application"

  - job_name: 'product-query-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'product-query-service:8080' ]
        labels:
          application: "Product Query Service Application"