server:
  port: 8080

app:
  eureka-server: discovery-server

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: lenn
    password: lenn
    url: jdbc:postgresql://postgres-product-command:5431/product-command-service